-- ============================================================
-- S.P.O.T.-IT — Monitoring Service Database Schema
-- Database: spotit_monitor_db
-- Tables:   rooms, registered_lab_items, detections, monitoring_logs
--
-- MICROSERVICES: This DB is ONLY for camera detection and room monitoring.
-- No user auth, claims, or profile data goes here.
-- ============================================================

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+08:00";
SET NAMES utf8mb4;

CREATE DATABASE IF NOT EXISTS `spotit_monitor_db`
  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `spotit_monitor_db`;

-- ── rooms ─────────────────────────────────────────────────────────────────────
-- One row per monitored laboratory room.
CREATE TABLE `rooms` (
  `room_id`            varchar(20)  NOT NULL COMMENT 'e.g. MLH306',
  `room_name`          varchar(150) NOT NULL,
  `floor`              varchar(30)  DEFAULT NULL COMMENT 'e.g. 3rd Floor MLH',
  `room_type`          varchar(60)  DEFAULT NULL COMMENT 'e.g. Computer Lab',
  `camera_count`       tinyint(4)   NOT NULL DEFAULT 2,
  `baseline_image`     varchar(300) DEFAULT NULL COMMENT 'Path to reference frame image',
  `baseline_count`     int(11)      NOT NULL DEFAULT 0 COMMENT 'Expected total item count',
  `monitoring_status`  enum('active','inactive','calibrating') NOT NULL DEFAULT 'inactive',
  `last_calibrated`    datetime     DEFAULT NULL,
  `is_active`          tinyint(1)   NOT NULL DEFAULT 1,
  `created_at`         datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`room_id`),
  KEY `idx_status`  (`monitoring_status`),
  KEY `idx_active`  (`is_active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── registered_lab_items ──────────────────────────────────────────────────────
-- Defines the ROI zones and expected items per room.
-- One row per inspection zone (e.g. "WS-07 Monitor Zone").
CREATE TABLE `registered_lab_items` (
  `item_id`            int(11)      NOT NULL AUTO_INCREMENT,
  `room_id`            varchar(20)  NOT NULL,
  `item_name`          varchar(150) NOT NULL COMMENT 'Human label e.g. Workstation 7 Monitor',
  `roi_label`          varchar(100) NOT NULL COMMENT 'Short code e.g. WS-07-MON',
  `baseline_image`     varchar(300) DEFAULT NULL COMMENT 'Reference frame crop for this ROI',
  `bounding_box`       json         DEFAULT NULL COMMENT '{x, y, w, h} in pixel coords',
  `tolerance_zone`     json         DEFAULT NULL COMMENT 'Expanded search zone {x, y, w, h}',
  `expected_count`     int(11)      NOT NULL DEFAULT 1,
  `tier`               enum('tier1','tier2','tier3','tier4') NOT NULL DEFAULT 'tier1',
  `tolerance_note`     varchar(300) DEFAULT NULL,
  `is_active`          tinyint(1)   NOT NULL DEFAULT 1,
  `registered_by`      int(11)      DEFAULT NULL COMMENT 'user_id from auth DB (denormalized)',
  `registered_at`      datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`item_id`),
  KEY `idx_room`   (`room_id`),
  KEY `idx_active` (`is_active`),
  FOREIGN KEY (`room_id`) REFERENCES `rooms`(`room_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── detections ────────────────────────────────────────────────────────────────
-- Every detection event generated by the Python/OpenCV module.
-- Python POSTs to auth/ingest_detection.php which inserts here.
CREATE TABLE `detections` (
  `detection_id`    int(11)      NOT NULL AUTO_INCREMENT,
  `room_id`         varchar(20)  NOT NULL,
  `object_type`     varchar(100) DEFAULT NULL COMMENT 'From ROI label e.g. Monitor',
  `object_zone`     varchar(150) DEFAULT NULL COMMENT 'Inspection zone label e.g. WS-07 Monitor Zone',
  `detected_at`     datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `snapshot_path`   varchar(300) DEFAULT NULL COMMENT 'Relative path in uploads/snapshots/',
  `snapshot_path_b` varchar(300) DEFAULT NULL COMMENT 'Second snapshot path, showing interaction/removal',
  `baseline_count`  int(11)      NOT NULL DEFAULT 0,
  `live_count`      int(11)      NOT NULL DEFAULT 0,
  `deviation`       int(11)      GENERATED ALWAYS AS (`live_count` - `baseline_count`) STORED,
  `roi_change_pct`  decimal(5,2) DEFAULT NULL COMMENT 'Percentage pixel change within ROI',
  `match_score`     decimal(4,3) DEFAULT NULL COMMENT '0.0-1.0 template match score',
  `status`          enum('pending','potential','confirmed_missing','dismissed','recovered')
                    NOT NULL DEFAULT 'pending',
  `notes`           text         DEFAULT NULL,
  `verified_by`     int(11)      DEFAULT NULL COMMENT 'user_id of staff who verified',
  `updated_at`      datetime     DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`detection_id`),
  KEY `idx_room`       (`room_id`),
  KEY `idx_status`     (`status`),
  KEY `idx_detected`   (`detected_at`),
  KEY `idx_deviation`  (`deviation`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── monitoring_logs ───────────────────────────────────────────────────────────
-- System-level event log: connections, recalibrations, user logins, errors.
CREATE TABLE `monitoring_logs` (
  `log_id`        int(11)      NOT NULL AUTO_INCREMENT,
  `room_id`       varchar(20)  DEFAULT NULL,
  `event_type`    varchar(80)  NOT NULL COMMENT 'e.g. user_login, recalibration, motion_pause',
  `event_message` text         DEFAULT NULL,
  `triggered_by`  int(11)      DEFAULT NULL COMMENT 'user_id if user-triggered',
  `logged_at`     datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`log_id`),
  KEY `idx_room`    (`room_id`),
  KEY `idx_type`    (`event_type`),
  KEY `idx_logged`  (`logged_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ── Seed: MLH rooms ───────────────────────────────────────────────────────────
INSERT INTO `rooms` (`room_id`, `room_name`, `floor`, `room_type`, `camera_count`, `baseline_count`, `monitoring_status`, `is_active`) VALUES
('MLH306', 'Systems & Application Development Lab', '3rd Floor MLH', 'Computer Lab', 2, 30, 'active', 1),
('MLH305', 'Logic and Algorithms Lab',              '3rd Floor MLH', 'Computer Lab', 2, 30, 'active', 1),
('MLH304', 'Engineering CAD Lab',                   '3rd Floor MLH', 'Computer Lab', 2, 25, 'active', 1),
('MLH303', 'Advanced Programming Lab',              '3rd Floor MLH', 'Computer Lab', 2, 30, 'active', 1),
('MLH301', 'Embedded Systems and Robotics Lab',     '3rd Floor MLH', 'Electronics Lab', 2, 18, 'active', 1),
('MLH203', 'Computational Engineering Lab',         '2nd Floor MLH', 'Computer Lab', 2, 20, 'active', 1),
('MLH201', 'Structured / Data Center Lab',          '2nd Floor MLH', 'Computer Lab', 2, 22, 'active', 1),
('MLH401', 'Architectural CAD Lab',                 '4th Floor MLH', 'Computer Lab', 2, 30, 'inactive', 1);

COMMIT;
